# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift01' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swift01

  target 'Swift01Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
