# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RACRun' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RACRun
  pod 'ReactiveObjC', '~> 3.1.1'
  target 'RACRunTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RACRunUITests' do
    # Pods for testing
  end

end
